// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "app": {
    "/": {
      "metadata": {
        "title": "Panel Starter",
        "description": "Panel starter template"
      },
      "components": {}
    }
  },
  "components": {
    "FallbackPages": {
      "home": "Home",
      "goBack": "Go back",
      "needHelp": "Need help?",
      "contactSupport": "Contact support",
      "actionsNavAriaLabel": "actions",
      "notFound": {
        "title": "Nothing to see here",
        "description": "Page you are trying to open does not exist. You may have mistyped the address, or the page has been moved to another URL."
      },
      "forbidden": {
        "title": "Access Denied",
        "description": "You don't have permission to access this resource. Contact an administrator if you believe this is an error."
      },
      "unauthorized": {
        "title": "Authentication Required",
        "description": "You need to sign in to access this page.",
        "signIn": "Sign in"
      },
      "error": {
        "title": "An error occurred",
        "description": "Please try again or contact support if the problem persists.",
        "tryAgain": "Try again"
      },
      "loading": {
        "ariaLabel": "Loading..."
      }
    },
    "dialog": {
      "close": "Close"
    },
    "sheet": {
      "close": "Close"
    },
    "ThemeToggle": {
      "toggleTheme": "Toggle theme"
    }
  },
  "hooks": {},
  "utils": {},
  "lib": {}
};
export default messages;